# Binary Classification with a Software Defects Dataset

## Importing libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.10.0'

## Data preprocessing

### Importing the datasets

In [3]:
df = pd.read_csv('train.csv')
X = df.iloc[:, 1:-1].values
y = df.iloc[:, -1].values

In [4]:
print(X)

[[ 22.   3.   1. ...  38.  22.   5.]
 [ 14.   2.   1. ...  18.  14.   3.]
 [ 11.   2.   1. ...  28.  17.   3.]
 ...
 [ 26.   1.   1. ...  51.  28.   1.]
 [ 10.   2.   1. ...  24.  19.   3.]
 [136.  18.  18. ... 162. 135.  35.]]


### Encoding categorical data

#### Encoding the dependent variable

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
# y = tf.keras.utils.to_categorical(y)

In [6]:
print(y)

[0 0 0 ... 0 0 0]


### Splitting the data into the Training set and the Test set

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

### Feature scaling

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Building the ANN

### Initializing the ANN

In [9]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [10]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [11]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [12]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Training the ANN

### Compiling the ANN

In [13]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [14]:
ann.fit(X_train, y_train, batch_size=64, epochs=100)

Epoch 1/100
1273/1273 [==============================] - 5s 3ms/step - loss: 0.4749 - accuracy: 0.7983
Epoch 2/100
1273/1273 [==============================] - 4s 3ms/step - loss: 0.4375 - accuracy: 0.8101
Epoch 3/100
1273/1273 [==============================] - 4s 3ms/step - loss: 0.4347 - accuracy: 0.8116
Epoch 4/100
1273/1273 [==============================] - 4s 3ms/step - loss: 0.4334 - accuracy: 0.8118
Epoch 5/100
1273/1273 [==============================] - 4s 3ms/step - loss: 0.4329 - accuracy: 0.8120
Epoch 6/100
1273/1273 [==============================] - 4s 3ms/step - loss: 0.4322 - accuracy: 0.8132
Epoch 7/100
1273/1273 [==============================] - 4s 3ms/step - loss: 0.4321 - accuracy: 0.8128
Epoch 8/100
1273/1273 [==============================] - 4s 3ms/step - loss: 0.4320 - accuracy: 0.8126
Epoch 9/100
1273/1273 [==============================] - 4s 3ms/step - loss: 0.4318 - accuracy: 0.8132
Epoch 10/100
1273/1273 [==============================] - 4s 3ms/step - l

1273/1273 [==============================] - 4s 3ms/step - loss: 0.4301 - accuracy: 0.8143
Epoch 80/100
1273/1273 [==============================] - 4s 3ms/step - loss: 0.4300 - accuracy: 0.8146
Epoch 81/100
1273/1273 [==============================] - 4s 3ms/step - loss: 0.4300 - accuracy: 0.8144
Epoch 82/100
1273/1273 [==============================] - 4s 3ms/step - loss: 0.4301 - accuracy: 0.8142
Epoch 83/100
1273/1273 [==============================] - 4s 3ms/step - loss: 0.4300 - accuracy: 0.8146
Epoch 84/100
1273/1273 [==============================] - 4s 3ms/step - loss: 0.4299 - accuracy: 0.8143
Epoch 85/100
1273/1273 [==============================] - 4s 3ms/step - loss: 0.4300 - accuracy: 0.8150
Epoch 86/100
1273/1273 [==============================] - 4s 3ms/step - loss: 0.4300 - accuracy: 0.8147
Epoch 87/100
1273/1273 [==============================] - 4s 3ms/step - loss: 0.4301 - accuracy: 0.8140
Epoch 88/100
1273/1273 [==============================] - 4s 3ms/step - loss:

## Predicting the Test set results

In [15]:
y_pred = ann.predict(X_test)

637/637 [==============================] - 2s 2ms/step


In [16]:
y_pred = (y_pred > 0.5)

## Making the Confusion Matrix

In [17]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[14890   863]
 [ 2856  1744]]


0.8172750945806515

## Predicting values for the test dataset

In [25]:
df_res = pd.read_csv('test.csv')
X_res = df_res.iloc[:, 1:].values

In [26]:
print(X_res)

[[ 33.   5.   1. ...  87.  57.   9.]
 [ 27.   8.   8. ...  70.  49.  15.]
 [130.  11.   7. ... 333. 244.  21.]
 ...
 [ 24.   2.   1. ...  36.  18.   3.]
 [ 18.   2.   1. ...  29.  22.   3.]
 [101.  15.  10. ...   0.   0.  29.]]


In [28]:
X_res = sc.transform(X_res)

In [29]:
y_res = ann.predict(X_res)

2121/2121 [==============================] - 5s 2ms/step


In [31]:
df_submission = pd.DataFrame(y_res)

In [32]:
df_submission.head()

0
0  0.267122
1  0.160339
2  0.701357
3  0.468077
4  0.129696

In [34]:
df_submission.columns = ["defects"]

In [37]:
df_submission = df_submission.rename(index = lambda x: x + 101763)

In [39]:
df_submission.to_csv("submission.csv")